ISSUE_INFO
superset
v1.3
16479
cooley-pe
2021-08-27T04:17:51Z
2021-09-06T12:04:11Z
not_pull_request
#bug,v1.3,
BEGIN_ISSUE
The `sync columns from source` button in the chart data source editor fails.

### Expected results
When I click the `sync column` button, superset will update the columns available in the chart per the data source.

### Actual results

I get an error and the column that was added to the datasource isn't available.

#### Screenshots

![Screen Shot 2021-08-26 at 9 04 54 PM](https://user-images.githubusercontent.com/64038793/131070293-2aba14da-4d4b-46f8-8d23-cdffa31eed02.png)

<img width="346" alt="Screen Shot 2021-08-26 at 9 16 50 PM" src="https://user-images.githubusercontent.com/64038793/131070987-82b84b9d-1dfe-4ee5-9b6b-39cb6f95998f.png">


#### How to reproduce the bug

1. Run a query in sqllab only selecting a subset of columns.
2. Click `Explore` to make a chart.
3. Click on `Edit datasource`
4. Add a column to the datasource
5. Click save
6. Click on `Edit datasource`
7. Click on the `Columns` tab.
8. Click `sync columns from source`

### Environment

(please complete the following information):

- superset version: `1.3`
- python version: `3.8.9`
- node.js version: n/a
- any feature flags active: 
  - ENABLE_TEMPLATE_PROCESSING
  - ALERT_REPORTS
  - DASHBOARD_CROSS_FILTERS
  - DASHBOARD_NATIVE_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.
COMMENT_INFO
villebro
2021-08-27T04:17:51Z
BEGIN_COMMENT
Thanks for reporting - I was able to reproduce on 1.3
COMMENT_INFO
villebro
2021-08-27T04:17:51Z
BEGIN_COMMENT
I have flagged the fix PRs for 1.3.1 (I will start working on rc1 this weekend).
COMMENT_INFO
heoun
2021-08-27T04:17:51Z
BEGIN_COMMENT
@villebro  - Heads up this is the error I get on my end when I try to sync. Might help narrow it down.
[Picture of the Error](https://imgur.com/a/84GC8JB)

COMMENT_INFO
villebro
2021-08-27T04:17:51Z
BEGIN_COMMENT
As a temporary workaround, you can rename the dataset to something without slashes (`/`), after which it should work ok
COMMENT_INFO
heoun
2021-08-27T04:17:51Z
BEGIN_COMMENT
My datasets don't have any slashes. Don't believe that is the issue here
COMMENT_INFO
villebro
2021-08-27T04:17:51Z
BEGIN_COMMENT
In that case please post more context on your problem so we can assess ehat the problem is (the problem in this issue has already been resolved)
COMMENT_INFO
cooley-pe
2021-08-27T04:17:51Z
BEGIN_COMMENT
@villebro I can confirm that the workaround seems to have fixed the issue on my end.
COMMENT_INFO
heoun
2021-08-27T04:17:51Z
BEGIN_COMMENT
@villebro - so potentially did some digging and it seems that my schema was not set when setting datasets through queries. Could be a bug from that end as well thats flowing into sync columns? Are there any workarounds to get charts to sync without having to recreate the dataset + charts from scratch?
COMMENT_INFO
villebro
2021-08-27T04:17:51Z
BEGIN_COMMENT
@heoun if you need to change the schema you should be able to do it in the save chart editor modal. If this doesn't work please open a new ticket with detailed reproduction steps. Closing this ticket as this bug is fixed on the forthcoming version 1.3.1.
