Make sure these boxes are checked before submitting your issue - thank you!  - [X] I have checked the superset logs for python stacktraces and included it here as text if there are any. - [X] I have reproduced the issue with at least the latest released version of superset. - [X] I have checked the issue tracker for the same issue and I haven't found one similar.    ### Superset version 0.28.1   ### Expected results I am expecting database connection is ok.   ### Actual results  I encountered an issue when adding a ms sql server to superset. I tried all the hints or solutions on Stack overflow and on here. Nothing works for me. I am using Windows and run the server under development.   The URI I am using is` 'mssql://@SERVER/DATABASE?driver=ODBC+Driver+13+for+SQL+Server'`.  Its weird that when I put the same URI in Python console to create engine using sqlalchemy.create_engine(URI), it works perfectly. It doesn't work when I put the URI in Adding database through Superset.   `sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 13 for SQL Server]SQL Server Network Interfaces: Error Locating Server/Instance Specified [xFFFFFFFF].  (-1) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. `  Could anyone help me with this? ### Steps to reproduce    
In Python use SqlAlchemy <img width="625" alt="capture" src="https://user-images.githubusercontent.com/15663112/51504003-30f0db80-1d93-11e9-8b68-d40d96b57378.PNG"> In Superset using same URI <img width="705" alt="capture" src="https://user-images.githubusercontent.com/15663112/51503643-fab25c80-1d90-11e9-8a67-87fd6e55a614.PNG">  
I have always had to do mssql+pyodbc. 
> I have always had to do mssql+pyodbc.  Hey thanks for the reply, I have tried the mssql + pyodbc which returns the same error as using mssql. I am suspecting it might be some IT restriction issue but it doesn't make sense since the same URI works perfectly on python console 
@wangym1993  I am using pymssql and this is the connection string I am using to connect to MS SQL  mssql+pymssql://<user>:<password>@localhost:1433/<db_name>.    
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions. For admin, please label this issue `.pinned` to prevent stale bot from closing the issue.  
