ISSUE_INFO
superset
v0.28
6842
prashant-shahi
2019-02-08T15:06:04Z
2019-02-26T01:45:16Z
not_pull_request
!deprecated-label:bug,v0.28,
BEGIN_ISSUE
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.


### Superset version
Superset 0.28.1
Flask 0.12.4
Python 3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]

### Expected results
Refreshing Druid metadata and listing latest datasources

### Actual results
Throws an error, instead of a warning for failing to connect to one of the clusters
```
Error while processing cluster 'x.x.x.x' HTTPConnectionPool(host='x.x.x.x', port=8082): Max retries exceeded with url: /druid/v2/datasources (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f414e6f9cf8>: Failed to establish a new connection: [Errno 111] Connection refused',)) 
```

### Steps to reproduce
Add an invalid druid cluster IP address along with a valid one. Then, refresh druid metadata
COMMENT_INFO
prashant-shahi
2019-02-08T15:06:04Z
BEGIN_COMMENT
This issue can be easily resolved by adding logic to not throw an exception but just a set of warning for those failed Druid Clusters.
COMMENT_INFO
prashant-shahi
2019-02-08T15:06:04Z
BEGIN_COMMENT
I can help if it is fine with you guys. :) 
COMMENT_INFO
mistercrunch
2019-02-08T15:06:04Z
BEGIN_COMMENT
For sure, help is always welcomed. 
COMMENT_INFO
prashant-shahi
2019-02-08T15:06:04Z
BEGIN_COMMENT
@mistercrunch Cool, here is the PR.

https://github.com/apache/incubator-superset/pull/6944
COMMENT_INFO
AdrianSanzRodrigo
2019-02-08T15:06:04Z
BEGIN_COMMENT
I'm getting same error...I cannot fetch any druid cluster. Any suggestion?
